version: '3'

services:
  prometheus:
    image: coffeeapplied/testbed-prometheus
    build:
      context: ./Monitoring/Prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"

  grafana:
    image: coffeeapplied/testbed-grafana
    build:
      context: ./Monitoring/Grafana
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  watchdog:
    image: coffeeapplied/testbed-watchdog
    build:
      context: ./Monitoring/Watchdog
      dockerfile: Dockerfile
    ports:
      - "8090:8090"

  fancy-service:
    image: coffeeapplied/testbed-fancy-service
    build:
      context: ./FancyService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"